version: '3'
services:
    gelf:
        build: .
        command: ["20"]
        stdin_open: true
        tty: true
        logging:
            driver: gelf
            options:
                gelf-address: "udp://54.202.68.205:12201"
                gelf-compression-type: "gzip"
                gelf-compression-level: "9"
                tag: "bob"
