version: '3'
services:
    logstash:
        container_name: logstash 
        image: docker.elastic.co/logstash/logstash:5.2.2
        network_mode: "host"
        stdin_open: true
        tty: true
        volumes:
            - ./pipeline:/usr/share/logstash/pipeline/:ro
            - ./logstash-config:/usr/share/logstash/config/:ro

    gelf:
        build: .
        command: ["60"]
        container_name: gelf-generator
        depends_on:
            - logstash
        logging:
            driver: gelf
            options:
                gelf-address: "udp://localhost:12201"
                gelf-compression-type: "gzip"
                gelf-compression-level: "9"
                tag: "nashua-jvm"
        network_mode: "host"
        stdin_open: true
        tty: true
