version: '3'
services:
    gelf:
        build: .
        command: ["100"]
        logging:
            driver: gelf
            options:
                gelf-address: "udp://10.0.2.113:12201"
                gelf-compression-type: "gzip"
                gelf-compression-level: "9"
                tag: "bob"